// Generated by Wrangler on Tue Apr 16 2024 10:21:42 GMT-0500 (Central Daylight Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  NI_DB: D1Database;
}
