// Generated by Wrangler on Fri Oct 18 2024 21:56:07 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	OPENAI_SECRET_KEY: string;
	OPENAI_ORG_ID: string;
	NEWS_API_ENDPOINT: string;
	NEWS_API_API_KEY: string;
	AUTH_SECRET: string;
	CHRONICLE_R2_ENDPOINT: string;
	CHRONICLE_R2_ACCESS_ID: string;
	CHRONICLE_R2_SECRET_KEY: string;
	CHRONICLE_R2_BUCKET_NAME: string;
	CHRONICLE_R2_TOKEN_VALUE: string;
	CHRONICLES_R2: R2Bucket;
	CHRONICLE_DB: D1Database;
}
