#:schema node_modules/wrangler/config-schema.json
name = "newsimages"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

# Bind a D1 database. D1 is Cloudflare’s native serverless SQL database.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#d1-databases
# [[d1_databases]]
# binding = "NI_DB"
# database_name = "news-images"
# database_id = "422fc2f2-d8ac-42ad-a3a6-7aef28770568"
