#:schema node_modules/wrangler/config-schema.json
name = "chronicle"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
keep_vars = true
pages_build_output_dir = ".vercel/output/static"

[placement]
mode = "smart"

[[d1_databases]]
binding = "CHRONICLE_DB"
database_name = "chronicleDB"
database_id = "adb02fff-468e-4b8c-921a-818d7f143d38"

[[r2_buckets]]
binding = "CHRONICLES_R2"
bucket_name = "chronicle-generated-images"

[triggers]
crons = ["0 0 * * *"]